name: taspoc
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_analytics: ^10.10.7
  firebase_remote_config: ^4.4.7
  cloud_firestore: ^4.8.2
  firebase_messaging: ^14.7.0
  firebase_crashlytics: ^3.5.7
  share_plus: ^10.0.2
  logger: ^2.5.0
  async: ^2.11.0
  barcode: ^2.2.8
  battery_plus: ^6.2.1
  collection: ^1.18.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.1
  flutter_inappwebview: ^6.1.5
  flutter_mobx: ^2.3.0
  flutter_slidable: ^3.1.2 
  flutter_svg: ^2.0.9
  open_file: ^3.5.10
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1
  text_mask: ^1.0.4
  url_launcher: ^6.3.1
  vibration: ^1.8.0
  video_player: ^2.9.2
  webview_flutter: ^4.10.0 
  youtube_player_flutter: ^9.1.1
  mockito: ^5.4.4
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^9.2.4
  device_info_plus: ^11.3.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_widget_from_html_core: ^0.15.2 
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  just_audio: ^0.9.43 
  local_auth: ^2.3.0
  mobx: ^2.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/badges/
    - assets/svgs/menu_left/
    - assets/svgs/
    - assets/images/
    - assets/audios/
    - assets/icons/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
